# Generated by Django 3.0.2 on 2020-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0004_auto_20200126_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='events',
            name='points',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], default=5, verbose_name='Оценка'),
        ),
    ]
