# Generated by Django 3.0.2 on 2021-05-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0007_auto_20210520_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('date_of_die', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmos.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
