# Generated by Django 3.0.2 on 2021-05-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0008_auto_20210520_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Awesome')], default=5, verbose_name='Оценка'),
        ),
    ]
